services:
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - library_link_backend-net
    ports:
      - "${HOST_DB_PORT}:5432"
    #volumes:
      #  - db-data:/var/lib/postgresql/data

networks:
  library_link_backend-net:

#volumes:
  #  db-data:
    #  name: "library_link_db-vol"

